stages:    
  - build 
  - auto_test 
cache:
    paths:
    - node_modules/    
  
build_master:
  stage: build 
  before_script:  
  - chcp 850 
  script:  
  - chcp 850 
  after_script: 
  - chcp 850 
  only:
  - triggers
  except:
  - developer 
  - schedules 
  - web
  tags:
  - master-runner  
     
  
build_developer:
  stage: build 
  before_script:   
  - echo "==>Run yarn install---------------------------"
  - chcp 850
  - yarn install
  - echo "==>install success-----------------------"  
  script: 
  - chcp 850 
  after_script: 
  - echo "==>Run yarn test------------------------------"
  - chcp 850
  - if "%CI_COMMIT_REF_NAME%"=="master" ( yarn build %build_webdeploy% ) else ( yarn test ) 
  - echo "==>test success--------------------------"    
  only: 
  - schedules
  - web  
  except:  
  - test
  tags:
  - developer-runner
  
  
 
   
