stages:    
  - build 
  - auto_test 
cache:
    paths:
    - node_modules/    
  
build_master:
  stage: build 
  before_script: 
  - echo "==>Run yarn install---------------------------"
  - chcp 850
  - yarn install
  - echo "==>install success-----------------------"    
  script: 
  - echo "==>Run yarn build------------------------------"
  - chcp 850
  - yarn build
  - echo "==>build success--------------------------"  
  after_script:
  - echo "==>Run yarn webdeploy------------------------------"
  - chcp 850
  - yarn webdeploy
  - echo "==>web deploy success--------------------------"  
  only:
  - triggers
  except:
  - developer 
  - schedules 
  - web
  tags:
  - master-runner  
     
  
build_developer:
  stage: build 
  before_script:   
  - echo "==>Run yarn install---------------------------"
  - chcp 850
  - yarn install
  - echo "==>install success-----------------------"  
  script: 
  - echo "==>Run yarn test build------------------------------"
  - chcp 850
  - yarn test
  - echo "==>test build success--------------------------"  
  after_script: 
  - echo "==>Run yarn test deploy------------------------------"
  - chcp 850
  - yarn testdeploy
  - echo "==>test deploy success--------------------------"    
  only: 
  - schedules
  - web  
  except:  
  - test
  tags:
  - developer-runner
  
  
 
   
